std = "lua51"
max_line_length = false -- StyLua owns formatting
ignore = { "212/self", "611", "612", "613", "614", "621" } -- implicit self (house ns: methods) + whitespace — StyLua owns the latter
exclude_files = { "Includes/", ".claude/" } -- vendored or session-local, never linted

-- The WoW API surface this add-on reads and never writes.
read_globals = {
	"BACKPACK_CONTAINER",
	"C_AddOns",
	"C_ChatInfo",
	"C_Container",
	"C_EventUtils",
	"C_Item",
	"C_PartyInfo",
	"C_QuestLog",
	"C_Seasons",
	"C_Spell",
	"C_Timer",
	"C_TooltipInfo",
	"ClearCursor",
	"ClickTradeButton",
	"CreateFrame",
	"CreateMacro",
	"CursorHasItem",
	"DeleteMacro",
	"EditMacro",
	"Enum",
	"format",
	"GameTooltip",
	"GetBuildInfo",
	"GetCursorInfo",
	"GetCVar",
	"GetGuildInfo",
	"GetItemStats",
	"GetLocale",
	"GetMacroIndexByName",
	"GetMacroInfo",
	"GetNormalizedRealmName",
	"GetNumMacros",
	"GetPhysicalScreenSize",
	"GetRealmName",
	"GetTime",
	"GetTradePlayerItemInfo",
	"GetTradePlayerItemLink",
	"hooksecurefunc",
	"InCombatLockdown",
	"IsInGroup",
	"IsInInstance",
	"IsInRaid",
	"IsPlayerSpell",
	"issecretvalue",
	"IsShiftKeyDown",
	"IsSpellKnown",
	"LE_PARTY_CATEGORY_INSTANCE",
	"LibStub",
	"LOCALIZED_CLASS_NAMES_MALE",
	"MAX_CHARACTER_MACROS",
	"MAX_TRADABLE_ITEMS",
	"NUM_BAG_SLOTS",
	"SetCVar",
	"Settings",
	"TooltipDataProcessor",
	"TradeFrame",
	"TradeFrame_GetAvailableSlot",
	"UIParent",
	"UnitClass",
	"UnitInParty",
	"UnitInRaid",
	"UnitIsInMyGuild",
	"UnitIsPlayer",
	"UnitIsUnit",
	"UnitLevel",
	"UnitName",
	"wipe",
	"WorldFrame",
}

-- The closed set of globals the add-on owns: its saved variables and its slash command.
globals = {
	"SLASH_WATERDISPENSER1",
	"WaterDispenserDB",
	SlashCmdList = { fields = { "WATERDISPENSER" } }, -- a field, so only the add-on's own slash entry is writable
}
